Update fixramdisk

diff --git a/source/usr/local/emhttp/plugins/dwsnap/scripts/fixramdisk b/source/usr/local/emhttp/plugins/dwsnap/scripts/fixramdisk
--- a/source/usr/local/emhttp/plugins/dwsnap/scripts/fixramdisk
+++ b/source/usr/local/emhttp/plugins/dwsnap/scripts/fixramdisk
@@ -15,8 +15,13 @@
 #
 echo "Recreating RAM disk..."
 
-umount /var/lib/snapraid 2>&1 | logger -t "snapraid-ramdisk"
-sleep 1
+umount -l /var/lib/snapraid 2>&1 | logger -t "snapraid-ramdisk"
+sleep 5
+
+if mountpoint -q /var/lib/snapraid; then 
+    echo "[error] Failed to unmount RAM disk (target busy?)... please retry again later!" | logger -t "snapraid-ramdisk"
+    exit 1
+fi
 
 rm -rf /var/lib/snapraid 2>&1 | logger -t "snapraid-ramdisk"
 mkdir -p /var/lib/snapraid 2>&1 | logger -t "snapraid-ramdisk"
