changes

diff --git a/source/usr/local/emhttp/plugins/dwsnap/scripts/write_config b/source/usr/local/emhttp/plugins/dwsnap/scripts/write_config
--- a/source/usr/local/emhttp/plugins/dwsnap/scripts/write_config
+++ b/source/usr/local/emhttp/plugins/dwsnap/scripts/write_config
@@ -27,7 +27,10 @@ rm -f /boot/config/plugins/dynamix/dwsnap*.cron
 
 for cfgfile in /boot/config/plugins/dwsnap/config/*.cfg; do
     # shellcheck disable=SC2015
-    [ -e "$cfgfile" ] && source "$cfgfile" || continue
+    if ! source "$cfgfile"; then
+        echo "write_config: Failed to parse SnapRAID array settings file '${cfgfile}' -- SKIPPED" | logger -t "snapraid-plugin"
+        continue
+    fi
     cfgname=$(basename --suffix=.cfg "$cfgfile")
 
     if [ "$CRON" == "hourly" ]; then
