Update snapraid-cron

diff --git a/source/usr/bin/snapraid-cron b/source/usr/bin/snapraid-cron
--- a/source/usr/bin/snapraid-cron
+++ b/source/usr/bin/snapraid-cron
@@ -106,10 +106,10 @@ trap signal_exit_cron SIGTERM
 if [ "$TOUCH" == "enable" ]; then
     RUNNINGOP="TOUCH"
     echo "### CRON -- Checking for files to be touched..." 2>&1 | tee -a /var/lib/snapraid/logs/snaplog
-    TIMESTATUS=$($SNAP_BIN -c $SNAP_CONF -l "/var/lib/snapraid/logs/cron-${LOGTIME}/status-${LOGTIME}.log" status 2>&1 | tee -a /var/lib/snapraid/logs/snaplog | grep -E 'You have [1-9][0-9]* files with( a)? zero sub-second timestamp\.')
+    TIMESTATUS=$($SNAP_BIN -c $SNAP_CONF -l "/var/lib/snapraid/logs/cron-${LOGTIME}/01a-status-${LOGTIME}.log" status 2>&1 | tee -a /var/lib/snapraid/logs/snaplog | grep -E 'You have [1-9][0-9]* files with( a)? zero sub-second timestamp\.')
     if [ -n "$TIMESTATUS" ]; then
         echo "### CRON -- Touching detected files..." 2>&1 | tee -a /var/lib/snapraid/logs/snaplog
-        if ! $SNAP_BIN -c $SNAP_CONF -l "/var/lib/snapraid/logs/cron-${LOGTIME}/touch-${LOGTIME}.log" $QUIETARG touch >>/var/lib/snapraid/logs/snaplog 2>&1; then
+        if ! $SNAP_BIN -c $SNAP_CONF -l "/var/lib/snapraid/logs/cron-${LOGTIME}/01b-touch-${LOGTIME}.log" $QUIETARG touch >>/var/lib/snapraid/logs/snaplog 2>&1; then
             echo "### CRON -- Touching detected files has failed... exiting" 2>&1 | tee -a /var/lib/snapraid/logs/snaplog
             FAILUREMSG="The touching of detected files has failed - check LOG."
             failure_exit_cron
@@ -128,7 +128,7 @@ if [ "$DIFF" == "enable" ]; then
     RUNNINGOP="DIFF"
     echo "### CRON -- Checking for differences..." 2>&1 | tee -a /var/lib/snapraid/logs/snaplog
     
-    DIFFS=$($SNAP_BIN -c $SNAP_CONF -l "/var/lib/snapraid/logs/cron-${LOGTIME}/diff-${LOGTIME}.log" diff 2>&1 | tee -a /var/lib/snapraid/logs/snaplog ; exit "${PIPESTATUS[0]}")
+    DIFFS=$($SNAP_BIN -c $SNAP_CONF -l "/var/lib/snapraid/logs/cron-${LOGTIME}/02-diff-${LOGTIME}.log" diff 2>&1 | tee -a /var/lib/snapraid/logs/snaplog ; exit "${PIPESTATUS[0]}")
     DIFFRET=$?
     if [ "$DIFFRET" -eq 0 ]; then
         OPTIME=$(date +"%d.%m.%Y %H:%M:%S %Z")
@@ -209,7 +209,7 @@ if [ "$SYNC" == "enable" ]; then
         fi
         if [ "$PREHASH" == "enable" ]; then
             echo "### CRON -- Prehashed Syncing...${FORCEZEROMSG}${SYNCERRORMSG}" 2>&1 | tee -a /var/lib/snapraid/logs/snaplog
-            if ! $SNAP_BIN -c $SNAP_CONF -l "/var/lib/snapraid/logs/cron-${LOGTIME}/hsync-${LOGTIME}.log" $QUIETARG -h $FORCEZEROARG $SYNCERRORARG sync >>/var/lib/snapraid/logs/snaplog 2>&1; then
+            if ! $SNAP_BIN -c $SNAP_CONF -l "/var/lib/snapraid/logs/cron-${LOGTIME}/03-hsync-${LOGTIME}.log" $QUIETARG -h $FORCEZEROARG $SYNCERRORARG sync >>/var/lib/snapraid/logs/snaplog 2>&1; then
                 echo "### CRON -- Prehashed Sync has failed, exiting..." 2>&1 | tee -a /var/lib/snapraid/logs/snaplog
                 FAILUREMSG="The prehashed sync has failed - check LOG."
                 failure_exit_cron
@@ -221,7 +221,7 @@ if [ "$SYNC" == "enable" ]; then
             fi
         else
             echo "### CRON -- Syncing...${FORCEZEROMSG}${SYNCERRORMSG}" 2>&1 | tee -a /var/lib/snapraid/logs/snaplog
-            if ! $SNAP_BIN -c $SNAP_CONF -l "/var/lib/snapraid/logs/cron-${LOGTIME}/sync-${LOGTIME}.log" $QUIETARG $FORCEZEROARG $SYNCERRORARG sync >>/var/lib/snapraid/logs/snaplog 2>&1; then
+            if ! $SNAP_BIN -c $SNAP_CONF -l "/var/lib/snapraid/logs/cron-${LOGTIME}/03-sync-${LOGTIME}.log" $QUIETARG $FORCEZEROARG $SYNCERRORARG sync >>/var/lib/snapraid/logs/snaplog 2>&1; then
                 echo "### CRON -- Sync has failed, exiting..." 2>&1 | tee -a /var/lib/snapraid/logs/snaplog
                 FAILUREMSG="The sync has failed - check LOG."
                 failure_exit_cron
@@ -249,7 +249,7 @@ if [ "$SCRUB" == "enable" ]; then
     if [ "$SCRUBNEW" == "enable" ]; then
         RUNNINGOP="SCRUBNEW"
         echo "### CRON -- Scrubbing New Blocks...${SCRUBERRORMSG}" 2>&1 | tee -a /var/lib/snapraid/logs/snaplog
-        if ! $SNAP_BIN -c $SNAP_CONF -l "/var/lib/snapraid/logs/cron-${LOGTIME}/scrubnew-${LOGTIME}.log" $QUIETARG -p new $SCRUBERRORARG scrub >>/var/lib/snapraid/logs/snaplog 2>&1; then
+        if ! $SNAP_BIN -c $SNAP_CONF -l "/var/lib/snapraid/logs/cron-${LOGTIME}/04a-scrubnew-${LOGTIME}.log" $QUIETARG -p new $SCRUBERRORARG scrub >>/var/lib/snapraid/logs/snaplog 2>&1; then
                 echo "### CRON -- Scrub New Blocks has failed, exiting..." 2>&1 | tee -a /var/lib/snapraid/logs/snaplog
                 FAILUREMSG="The new block scrub has failed - check LOG."
                 failure_exit_cron
@@ -263,7 +263,7 @@ if [ "$SCRUB" == "enable" ]; then
     fi
     RUNNINGOP="SCRUB"
     echo "### CRON -- Scrubbing [${SCRUBPERCENT} % / ${SCRUBAGE} days age]...${SCRUBERRORMSG}" 2>&1 | tee -a /var/lib/snapraid/logs/snaplog
-    if ! $SNAP_BIN -c $SNAP_CONF -l "/var/lib/snapraid/logs/cron-${LOGTIME}/scrub-${LOGTIME}.log" $QUIETARG -p "$SCRUBPERCENT" -o "$SCRUBAGE" $SCRUBERRORARG scrub >>/var/lib/snapraid/logs/snaplog 2>&1; then
+    if ! $SNAP_BIN -c $SNAP_CONF -l "/var/lib/snapraid/logs/cron-${LOGTIME}/04b-scrub-${LOGTIME}.log" $QUIETARG -p "$SCRUBPERCENT" -o "$SCRUBAGE" $SCRUBERRORARG scrub >>/var/lib/snapraid/logs/snaplog 2>&1; then
             echo "### CRON -- Scrub has failed, exiting..." 2>&1 | tee -a /var/lib/snapraid/logs/snaplog
             FAILUREMSG="The scrub has failed - check LOG."
             failure_exit_cron
