bash improvements

diff --git a/source/usr/bin/snapraid-cron b/source/usr/bin/snapraid-cron
--- a/source/usr/bin/snapraid-cron
+++ b/source/usr/bin/snapraid-cron
@@ -45,6 +45,10 @@ if [ ! -f "$SNAP_CONF" ] || [ ! -f "$CONFIG" ]; then
 fi
 
 if pgrep -f "^(/usr/bin/ionice -c [0-9] )?/usr/bin/snapraid -c ${SNAP_CONF}" >/dev/null 2>&1 || pgrep -f "^(/bin/bash )?/usr/bin/snapraid-runner ${CFGNAME}" >/dev/null 2>&1; then
+    echo "A backend helper program that facilitates SnapRAID's periodic array maintenance."
+    echo "Usage: snapraid-cron <array name>"
+    echo "-- <array name>: name of the array configuration to perform the operation on (example: primary)"
+    echo ""
     echo "(${CFGNAME}) SnapRAID is already running on the specified array, exiting..." | logger -s -t "snapraid-cron"
     exit 1
 fi
@@ -53,10 +57,21 @@ RUNNINGOP="INIT"
 
 [ ! -d "/var/lib/snapraid/logs/${CFGNAME}" ] && mkdir -p "/var/lib/snapraid/logs/${CFGNAME}"
 
-[ -e "$CONFIG" ] && source "$CONFIG"
+if ! source "$CONFIG"; then
+    echo "A backend helper program that facilitates SnapRAID's periodic array maintenance."
+    echo "Usage: snapraid-cron <array name>"
+    echo "-- <array name>: name of the array configuration to perform the operation on (example: primary)"
+    echo ""
+    echo "(${CFGNAME}) SnapRAID plugin configuration cannot be parsed, exiting..." | logger -s -t "snapraid-runner"
+    exit 1
+fi
 
 if [ "$CRON" != "hourly" ] && [ "$CRON" != "daily" ] && [ "$CRON" != "weekly" ] && [ "$CRON" != "monthly" ]; then
-    echo "(${CFGNAME}) SnapRAID maintenance not enabled in array settings, exiting..." | logger -s -t "snapraid-cron"
+    echo "A backend helper program that facilitates SnapRAID's periodic array maintenance."
+    echo "Usage: snapraid-cron <array name>"
+    echo "-- <array name>: name of the array configuration to perform the operation on (example: primary)"
+    echo ""
+    echo "(${CFGNAME}) SnapRAID maintenance is not enabled in array settings, exiting..." | logger -s -t "snapraid-cron"
     exit 1
 fi
 
diff --git a/source/usr/bin/snapraid-runner b/source/usr/bin/snapraid-runner
--- a/source/usr/bin/snapraid-runner
+++ b/source/usr/bin/snapraid-runner
@@ -61,6 +61,8 @@ else
     echo "-- <array name>: name of the array configuration to perform the operation on (example: primary)"
     echo "-- <0|1>: send notifications once the operation completes (0:no/1:yes)"
     echo "-- [options]: optional parameters for the requested operation (see SnapRAID manual)"
+    echo ""
+    echo "(${CFGNAME}) No valid notification setting was provided, exiting..." | logger -s -t "snapraid-runner"
     exit 1
 fi
 
@@ -76,17 +78,34 @@ if [ ! "$CMDKNOWN" == "YES" ]; then
     echo "-- <array name>: name of the array configuration to perform the operation on (example: primary)"
     echo "-- <0|1>: send notifications once the operation completes (0:no/1:yes)"
     echo "-- [options]: optional parameters for the requested operation (see SnapRAID manual)"
+    echo ""
+    echo "(${CFGNAME}) No valid operation command was provided, exiting..." | logger -s -t "snapraid-runner"
     exit 1
 fi
 
 if pgrep -f "^(/usr/bin/ionice -c [0-9] )?/usr/bin/snapraid -c ${SNAP_CONF}" >/dev/null 2>&1 || pgrep -f "^(/bin/bash )?/usr/bin/snapraid-cron ${CFGNAME}" >/dev/null 2>&1; then
+    echo "A backend helper program that facilitates communication between SnapRAID and UNRAID's web interface."
+    echo "Usage: snapraid-runner <array name> <0|1> status|diff|sync|scrub|list|dup|up|down|touch|smart|pool|check|fix [options]"
+    echo "-- <array name>: name of the array configuration to perform the operation on (example: primary)"
+    echo "-- <0|1>: send notifications once the operation completes (0:no/1:yes)"
+    echo "-- [options]: optional parameters for the requested operation (see SnapRAID manual)"
+    echo ""
     echo "(${CFGNAME}) SnapRAID is already running on the specified array, exiting..." | logger -s -t "snapraid-runner"
     exit 1
 fi
 
 [ ! -d "/var/lib/snapraid/logs/${CFGNAME}" ] && mkdir -p "/var/lib/snapraid/logs/${CFGNAME}"
 
-[ -e "$CONFIG" ] && source "$CONFIG"
+if ! source "$CONFIG"; then
+    echo "A backend helper program that facilitates communication between SnapRAID and UNRAID's web interface."
+    echo "Usage: snapraid-runner <array name> <0|1> status|diff|sync|scrub|list|dup|up|down|touch|smart|pool|check|fix [options]"
+    echo "-- <array name>: name of the array configuration to perform the operation on (example: primary)"
+    echo "-- <0|1>: send notifications once the operation completes (0:no/1:yes)"
+    echo "-- [options]: optional parameters for the requested operation (see SnapRAID manual)"
+    echo ""
+    echo "(${CFGNAME}) SnapRAID plugin configuration cannot be parsed, exiting..." | logger -s -t "snapraid-runner"
+    exit 1
+fi
 
 if [ -x "/usr/bin/ionice" ]; then
     [ "$PRIO" == "idle" ] && SNAP_BIN="/usr/bin/ionice -c 3 /usr/bin/snapraid"
